feat: allow preview of subsections of the wiki
boxfish-studio/iota-wiki pull request #37
Opened 2023-10-24 11:52 UTC by VmMad

# Description of change

Modify the start command of the CLI to allow selecting the desired section of the wiki to preview.
Add scripts to start a subsection of the wiki directly: `yarn start:{section}`
Handle the selection of sections of the wiki by splitting the config and selecting with environment variable.

## Links to any relevant issues

Closes #31.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the [contribution guidelines](https://github.com/iota-wiki/iota-wiki/blob/main/.github/CONTRIBUTING.md) for this project
- [x] I have performed a self-review of my own changes
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-10-24 14:34 UTC, marc2332 approved these changes
:fire:

2023-10-26 09:59 UTC, begonaalvarezd requested changes

2023-10-26 09:59 UTC, begonaalvarezd commented on cli/src/commands/build.tsx
Lets remove the changes of the CLI 🙏🏼

2023-10-26 09:59 UTC, begonaalvarezd commented on contentPlugins.js
> +  const maintainPlugin = [
why changing this from plural to singular when its an array?

2023-10-26 09:59 UTC, begonaalvarezd commented on contentPlugins.js
> +  const getStartedPlugin = [{
why changing this from plural to singular when its an array?

2023-10-26 09:59 UTC, begonaalvarezd commented on contentPlugins.js
> +  const learnPlugin = [{
why changing this from plural to singular when its an array?

2023-10-26 14:11 UTC, begonaalvarezd approved these changes

2023-10-27 15:41 UTC, begonaalvarezd commented
superseeded by https://github.com/iotaledger/iota-wiki/pull/1292

2023-10-27 15:41 UTC, closed without merging